webapp/blueprints/aum/__init__.py
from webapp.blueprints.aum.views import aum

webapp/blueprints/aum/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from webapp import role_required
from webapp.models.user_auth import User, AuthValidationError
import re

aum = Blueprint('aum', __name__, template_folder='templates',
                static_folder='static',
                static_url_path='/aum/static')


@aum.before_request
@role_required('ADMIN')
def before_request():
    """ Protect all of the admin endpoints. """
    pass


@aum.route('/', methods=['GET'])
def index():
    return render_template('aum/index.html', user_list=User.get_list())


@aum.route('/user_add', methods=['GET', 'POST'])
def user_add():
    if request.method == 'GET':
        return render_template('aum/user.html', new_user=True)
    if request.method == 'POST':
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        email = request.form.get('email')
        password = request.form.get('password')
        role = request.form.get('role')
        if request.form.get('active'):
            active = True
        else:
            active = False

        # if this returns a user, then the email already exists in database
        # if a user is found, we want to redirect back to start page
        if User.get_by_mail(email):
            flash('Email address already exists', 'alert-danger')
            return redirect(url_for('aum.user_add'))

        # create new user with the form data. Hash the password so plaintext
        # version isn't saved.
        new_user = User(fname, lname, email, password, role, active)
        User.create(new_user)

        flash(f'User Created Successfully', 'alert-success')
        return redirect(url_for('aum.index'))


@aum.route('/user_modify/<int:id>', methods=['GET', 'POST'])
def user_modify(id):
    if request.method == 'GET':
        return render_template('aum/user.html', new_user=False, user=User.get(id))

    if request.method == 'POST':
        if request.form.get('active'):
            active = True
        else:
            active = False

        try:
            User.modify(id,
                        request.form.get('fname'),
                        request.form.get('lname'),
                        request.form.get('email'),
                        request.form.get('email'),
                        request.form.get('role'),
                        active)

            flash(f'User Updated Successfully', 'alert-success')
            return redirect(url_for('aum.index'))

        except AuthValidationError as exception:
            flash(f'{exception}', 'alert-danger')
            return render_template('aum/user.html', new_user=False, user=User.get(id))


@aum.route('/user_delete/<int:id>')
def user_delete(id):
    try:
        User.delete(id)
        flash(f'User Deleted Successfully', 'alert-success')
        return redirect(url_for('aum.index'))
    except AuthValidationError as exception:
        flash(f'Failed to delete user', 'alert-danger')
        return redirect(url_for('aum.index'))


@aum.route('/user_validate_mail/<email>')
def user_validate_mail(email):
    # Checks if the email address is valid
    # Checks if the email address exists in DB
    mail_address_regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
    if (re.fullmatch(mail_address_regex, email)):
        if User.email_exists(email):
            message = {'status': 'NOK', 'message': 'Existing email found'}
        else:
            message = {'status': 'OK', 'message': ''}
    else:
        message = {'status': 'NOK', 'message': 'Invalid email address'}

    return jsonify(message)


@aum.route('/change_password/<int:id>', methods=['POST'])
def change_password(id):
    print(request.form.get('password'))
    if request.method == 'POST':
        try:
            User.set_password(id, request.form.get('password'))
            flash(f'Password changed successfully', 'alert-success')
            return render_template('aum/user.html', new_user=False, user=User.get(id))
        except AuthValidationError as exception:
            flash(f'Password change failed', 'alert-danger')
            return render_template('aum/user.html', new_user=False, user=User.get(id))

webapp/blueprints/aum/templates/aum/components/modals/login.html
{% block modal %}
<!-- Edit Login Modal HTML -->
<div id="loginModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content bg-dark p-3">
            <h5 class="text-center fw-light text-light">Login</h5>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
            {% endif %}
            {% endwith %}
            <form method="POST" action="{{ url_for('auth.login') }}">
                <div class="form-outline mb-4">
                    <label for="username" class="form-label text-light">Username</label>
                    <input type="email" name="username" placeholder="Your Email Address" class="form-control">
                </div>
                <div class="form-outline mb-4">
                    <label for="password" class="form-label text-light">Password</label>
                    <input type="password" name="password" placeholder="Your Password" class="form-control">
                </div>
                <div>
                    <div class="d-grid pt-2">
                        <button class="btn btn-primary btn-login fw-bold" type="submit">Sign in</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

webapp/blueprints/aum/templates/aum/components/modals/password.html
{% block modal %}
{% if not new_user %}
<!-- Edit Password Change Modal HTML -->
<div id="passwordModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content bg-dark p-3">
            <h5 class="text-center fw-light text-light">Change Password</h5>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
            {% endif %}
            {% endwith %}
            <form method="POST" action="{{ url_for('aum.change_password', id=user.id) }}">
                <div class="form-outline mb-4">
                    <label for="password" class="form-label text-light">Enter New Password</label>
                    <input type="password" name="password" placeholder="New Password" class="form-control">
                </div>
                <div>
                    <div class="d-grid pt-2">
                        <button class="btn btn-primary btn-login fw-bold" type="submit">Update Password</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

webapp/blueprints/aum/templates/aum/components/nav/nav.html
{% block nav %}
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">CRUD Example</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page"
                        href="{{ url_for('main.index') }}">Item 1</a></li>
                {% if current_user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active" aria-current="page"
                        href="{{ url_for('auth.logout') }}">Logout</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Item 1</a></li>
                        <li><a class="dropdown-item" href="#">Item 2</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('aum.index') }}">Admin User Management</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" data-bs-toggle="modal" href="#login"
                        data-bs-target="#loginModal">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

webapp/blueprints/aum/templates/aum/components/scripts/validate.html
<script>
    var button = document.getElementById("btn");
    var email = document.getElementById("email");
    var server_path = "/aum/user_validate_mail/";

    async function checkEmailValidity(el) {

        button.classList.add('loading');

        var valid = await validateEmail(el.value);

        if (valid) {
            el.classList.add("is-valid");
            el.classList.remove("is-invalid");
            el.setCustomValidity("");
            validationEmail.classList.remove("invalid-tooltip");
            validationEmail.classList.add("valid-tooltip");
        } else {
            el.classList.remove("is-valid");
            el.classList.add("is-invalid");
            el.setCustomValidity("invalid");
            validationEmail.classList.remove("valid-tooltip");
            validationEmail.classList.add("invalid-tooltip");
        }

        button.classList.remove('loading');

        return valid;

    }

    async function validateEmail(val) {

        let email_url = server_path + email.value;
        var result = await fetch(email_url)
            .then(function (res) {
                return res.json();
            })
            .then(function (json) {
                if (json.message != null) validationEmail.textContent = json.message;
                console.log(json.message);
                return (json.status == 'OK');
            });

        return result;

    }

    email.addEventListener('blur', function (event) {
        if (event.relatedTarget != button) checkEmailValidity(this);
    }, false);

    email.addEventListener('change', function (event) {
        this.classList.remove("is-invalid");
        this.setCustomValidity("");
    }, false);
</script>

webapp/blueprints/aum/templates/aum/index.html
{% extends "base.html" %}

<!-- Header Modification-->
{% block head %}
{{ super() }}
<title>Admin User Management</title>

{% endblock %}

<!-- Navigation -->
{% block nav %}
{% include "aum/components/nav/nav.html" %}
{% endblock %}

<!-- Page content-->
{% block content %}
<div class="container-lg">
  <div class="text-center mt-3">
    <h1>Admin User Management</h1>
  </div>
</div>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="row">
  <div class="col d-none d-sm-grid"></div>
  <div class="col">
    {% for category, message in messages %}
    <div style="margin-bottom: -50px" class="alert {{ category }} text-center" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  </div>
  <div class="col d-none d-sm-grid"></div>
</div>
{% endif %}
{% endwith %}
<div class="container-lg mt-5">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Name</th>
        <th scope="col" class="d-none d-sm-table-cell">Level</th>
        <th scope="col" class="d-none d-sm-table-cell">State</th>
        <th scope="col" class="">
          <a class="btn btn-success btn-sm px-3 mx-3" href="{{ url_for('aum.user_add') }}">Add User</a>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for user in user_list %}
      <tr>
        <td class="">{{user.email}}</td>
        <td>{{user.fname + " " + user.lname}}</td>
        <td class="d-none d-sm-table-cell">{{user.role | capitalize}}</td>
        {% if user.active%}
        <td class="d-none d-sm-table-cell">Enabled</td>
        {% else %}
        <td class="d-none d-sm-table-cell">Disabled</td>
        {% endif %}
        <td>
          <div class="btn-group-sm btn">
            <a class="btn btn-primary btn-sm px-3 mb-1 mb-sm-0"
              href="{{ url_for('aum.user_modify', id=user.id) }}">Edit</a>
            <a class="btn btn-danger btn-sm" href="{{ url_for('aum.user_delete', id=user.id) }}">Delete</a>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock %}

<!-- Modals-->
{% block modal %}
{% include "aum/components/modals/login.html" %}
{% endblock %}

webapp/blueprints/aum/templates/aum/user.html
{% extends "base.html" %}

<!-- Header Modification-->
{% block head %}
{{ super() }}
<title>Admin User Management</title>

{% endblock %}

<!-- Navigation -->
{% block nav %}
{% include "aum/components/nav/nav.html" %}
{% endblock %}

<!-- Page content-->
{% block content %}
{% if new_user %}
<div class="container">
    <div class="text-center mt-3">
        <h1>Add New Admin User</h1>
    </div>
</div>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="row">
    <div class="col d-none d-sm-grid"></div>
    <div class="col">
        {% for category, message in messages %}
        <div style="margin-bottom: -50px" class="alert {{ category }} text-center" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    <div class="col d-none d-sm-grid"></div>
</div>
{% endif %}
{% endwith %}
<div class="container mt-5">
    <div class="row">
        <div class="mx-auto col-8 col-md-8 col-lg-6">
            <form method="POST" action="{{ url_for('aum.user_add') }}">
                <div class="form-group mb-2 position-relative">
                    <label for="email">Email address</label>
                    <input id="email" type="text" class="form-control" name="email" aria-describedby="emailHelp"
                        placeholder="Enter email" required>
                    <div id="validationEmail" class="invalid-tooltip"></div>
                </div>

                <div class="form-group mb-2">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
                <div class="form-group mb-2">
                    <label for="fname">Firstname</label>
                    <input type="fname" class="form-control" name="fname" placeholder="Firstname" required>
                </div>
                <div class="form-group mb-2">
                    <label for="lname">Lastname</label>
                    <input type="lname" class="form-control" name="lname" placeholder="Lastname" required>
                </div>
                <div class="form-group mb-2">
                    <label for="role">Select User Role</label>
                    <select name="role" class="form-control">
                        <option value="ADMIN" selected>Admin</option>
                        <option value="MANAGER">Manager</option>
                    </select>
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="checkbox" name="active">
                    <label class="form-check-label" for="gridCheck">
                        Enable User
                    </label>
                </div>
                <div class="pt-2 text-center">
                    <button id="btn" type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% else %}
<!-- Edit a existing user   --------------------------------------->
<div class="container">
    <div class="text-center mt-3">
        <h1>Edit User</h1>
    </div>
</div>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="row">
    <div class="col d-none d-sm-grid"></div>
    <div class="col">
        {% for category, message in messages %}
        <div style="margin-bottom: -50px" class="alert {{ category }} text-center" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    <div class="col d-none d-sm-grid"></div>
</div>
{% endif %}
{% endwith %}
<div class="container mt-5">
    <div class="row">
        <div class="mx-auto col-8 col-md-8 col-lg-6">
            <form method="POST" action="{{ url_for('aum.user_modify', id=user.id) }}">
                <div class="form-group mb-2">
                    <label for="email">Email address</label>
                    <input id="email" type="text" class="form-control" name="email" aria-describedby="emailHelp"
                        placeholder="Enter email" value="{{user.email}}" required>
                    <div id="validationEmail" class="invalid-tooltip"></div>
                </div>

                <!-- <div class="form-group mb-2">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div> -->
                <div class="form-group mb-2">
                    <label for="fname">Firstname</label>
                    <input type="fname" class="form-control" name="fname" placeholder="Firstname" value="{{user.fname}}"
                        required>
                </div>
                <div class="form-group mb-2">
                    <label for="lname">Lastname</label>
                    <input type="lname" class="form-control" name="lname" placeholder="Lastname" value="{{user.lname}}"
                        required>
                </div>
                <div class="form-group mb-2">
                    <label for="role">Select User Role</label>
                    <select name="role" class="form-control">
                        {% if user.role == 'ADMIN' %}
                        <option value="ADMIN" selected>Admin</option>
                        <option value="MANAGER">Manager</option>
                        {% else %}
                        <option value="ADMIN">Admin</option>
                        <option value="MANAGER" selected>Manager</option>
                        {% endif %}
                    </select>
                </div>
                <div class="form-check mb-2">
                    {% if user.active %}
                    <input class="form-check-input" type="checkbox" name="active" checked>
                    {% else %}
                    <input class="form-check-input" type="checkbox" name="active">
                    {% endif %}
                    <label class="form-check-label" for="gridCheck">
                        Enable User
                    </label>
                </div>
                <div class="pt-2 text-center">
                    <button id="btn" type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="pt-4 text-center">
                    <a class="btn btn-primary" data-bs-toggle="modal" href="#changepassword"
                        data-bs-target="#passwordModal">Change
                        Password</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

<!-- Modals-->
{% block modal %}
{% include "aum/components/modals/password.html" %}
{% endblock %}

<!-- Scripts-->
{% block scripts %}
{% include "aum/components/scripts/validate.html" %}
{% endblock %}